epc<-read.table("household_power_consumption.txt",header=TRUE, sep=";", skip= 66636, nrows= 2880, col.names = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
epc$DateTime <- strptime(paste (epc$Date, epc$Time, sep=" "),"%d/%m/%Y %H:%M:%S")
with(epc, plot(DateTime,Sub_metering_1,type="l",xlab="", ylab="Energy sub metering"))
with(epc, points(DateTime,Sub_metering_2, type="l",col="red"))
with(epc, points(DateTime,Sub_metering_3, type="l",col="blue"))
legend("topright",pch="_",col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,"plot3.png")
dev.off()