epc<-read.table("household_power_consumption.txt",header=TRUE, sep=";", skip= 66636, nrows= 2880, col.names = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
epc$DateTime <- strptime(paste (epc$Date, epc$Time, sep=" "),"%d/%m/%Y %H:%M:%S")
with(epc, plot(DateTime,Global_active_power,type="l",xlab="", ylab="Global Active Power (kilowatts)"))
dev.copy(png,"plot2.png")
dev.off()
